apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-svc

spec:
  replicas: 1
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: community-svc

  template:
    metadata:
      labels:
        app: community-svc

    spec:
      containers:
        - name: community-svc
          image: eonmsa/community-svc:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8083

          envFrom:
            - configMapRef:
                name: community-config
            - secretRef:
                name: community-secret
                
