apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-svc

spec:
  replicas: 1
  revisionHistoryLimit: 2

  selector:
    matchLabels:
      app: challenge-svc

  template:
    metadata:
      labels:
        app: challenge-svc

    spec:
      containers:
        - name: challenge-svc
          image: eonmsa/challenge-svc:v11
          imagePullPolicy: Always

          ports:
            - containerPort: 8084

          envFrom:
            - configMapRef:
                name: challenge-config
            - secretRef:
                name: challenge-secret

          volumeMounts:
            - name: challenge-uploads
              mountPath: /app/uploads

      volumes:
        - name: challenge-uploads
          persistentVolumeClaim:
            claimName: challenge-uploads-pvc