apiVersion: v1
kind: ConfigMap
metadata:
    name: recommendation-config

data:
    NODE_ENV: "production"
    PORT: "8085"

    DB_HOST: "mysql"
    DB_PORT: "3306"
    DB_NAME: "recommendation_db"
    DB_USER: "root"

    REDIS_HOST: "redis"
    REDIS_PORT: "6379"
