apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-svc

spec:
  replicas: 1

  selector:
    matchLabels:
      app: recommendation-svc

  template:
    metadata:
      labels:
        app: recommendation-svc

    spec:
      containers:
        - name: recommendation-svc
          image: eonmsa/recommendation-svc:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8085

          envFrom:
            - configMapRef:
                name: recommendation-config
            - secretRef:
                name: recommendation-secret