apiVersion: v1
kind: ConfigMap
metadata:
    name: schedule-config

data:
    NODE_ENV: "production"
    PORT: "8082"

    DB_HOST: "mysql"
    DB_PORT: "3306"
    DB_NAME: "schedule_db"
    DB_USER: "root"

    REDIS_HOST: "redis"
    REDIS_PORT: "6379"

    USER_SERVICE_URL: "http://user-svc:8081"
    MY_SCHOOL_CACHE_TTL_SECONDS: "86400"
