apiVersion: v1
kind: Secret
metadata:
  name: schedule-secret

type: Opaque
stringData:
  DB_PASSWORD: "our_db_password"
  NEIS_API_KEY: "YOUR_NEIS_KEY"
  MOLIT_API_KEY: "YOUR_MOLIT_KEY"
  INTERNAL_API_SECRET: "YOUR_INTERNAL_API_SECRET"